name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
repository: https://github.com/redhotsixbull/packages/tree/main/packages/camera/camera

version: 0.10.5+3

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation
      web:
        default_package: camera_web

dependencies:
  camera_android:
    git:
      url: https://github.com/redhotsixbull/packages.git
      path: packages/camera/camera_android
  camera_avfoundation:
    git:
      url: https://github.com/redhotsixbull/packages.git
      path: packages/camera/camera_avfoundation
  camera_platform_interface:
    git:
      url: https://github.com/redhotsixbull/packages.git
      path: packages/camera/camera_platform_interface
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2
  quiver: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.0
  plugin_platform_interface: ^2.0.0
  video_player: ^2.0.0
