name: camera_platform_interface
description: A common platform interface for the camera plugin.
repository: https://github.com/redhotsixbull/packages/tree/main/packages/camera/camera_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.5.2

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cross_file: ^0.3.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
